language: ruby
sudo: false
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
before_install:
  - gem update --system # https://github.com/rubygems/rubygems/pull/1819
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
